### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Esterze** [Sna-aaa/esx-sna-fuel#3]
Is it possible to use the `GetFuelLevel(veh)` instead?
The HUD I use is closed source and changing the export isn't possible.

**Comment by Sna-aaa** [comment]
unfortunately this is not possible as GetFuelLevel lead to strange effects when there is nearly no fuel, this is a fivem bug so i can't avoid to use the exports
You know you can always ask the developer to have a configurable export for the fuel in the closed source, it is something i do without problem, and if you payed the script it is normal to support customers

**Comment by Esterze** [comment]
I asked. The developer either doesn't care or is too lazy to implement such an easy to implement feature.

**Comment by Esterze** [comment]
I guess I'll use the trew's hud again.

**Comment by Esterze** [comment]
> and if you payed the script it is normal to support customers

Paid* 😆
I won the hud, but yes, support should be provided either way

**Comment by Sna-aaa** [comment]
haha i see, so in this case yes you will need to come back to your old hud....
Sad an author can't handle the encryption correctly for a paid resource
