### ISSUE TITLE
2 issues: Getting error while using admin /fuel. and cannot get jerrican to work on vehicles.

### ISSUE THREAD

**Issue by MaliciousSnip3r** [Sna-aaa/esx-sna-fuel#4]
![fuel](https://user-images.githubusercontent.com/68460112/222896804-5e86efed-44f2-45b7-add3-301cfff4190d.png)
^^ using command

Ive used ox target and walked around car with weapon_petrolcan in hand and cannot get any prompt to refill car.

**Comment by MaliciousSnip3r** [comment]
Any ideas?

**Comment by Sna-aaa** [comment]
Hello,
The command is corrected in the last version :) 
I've also added comment for jerrican in the readme
