### ISSUE TITLE
Edit everywhere where LegacyFuel stands

### ISSUE THREAD

**Issue by maxcamorra** [Sna-aaa/esx-sna-fuel#5]
How do I edit the exports where LegacyFuel is used when the source code of a script is encrypted?

**Comment by Sna-aaa** [comment]
Just ask the developper to who you gave money to make his script correctly and allow the user to change this by moving it in the config
The encryption is not meant to hide you things it is just to avoid copies, not all the code needs to be crypted to be safe. And only the developper can change his encrypted code
